# Use postgres/example user/password credentials
version: "3.8"
services:
  postgres:
    image: postgres:13
    container_name: postgres
    expose:
    - 5432
    ports:
      - 5432:5432
    environment:
         - POSTGRES_PASSWORD=admin
         - POSTGRES_USER=admin
         - POSTGRES_DB=agendamentodb